// Command cogo is the thin terminal face over internal/core. It validates
// core against a real vault. The MCP server face (later) is the same binary.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/diegoparras/cogo/internal/agentsmd"
	"github.com/diegoparras/cogo/internal/contra"
	"github.com/diegoparras/cogo/internal/core"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	args := os.Args[2:]
	var err error
	switch os.Args[1] {
	case "init":
		err = cmdInit(args)
	case "add":
		err = cmdAdd(args)
	case "pack":
		err = cmdPack(args)
	case "search":
		err = cmdSearch(args)
	case "stale":
		err = cmdStale(args)
	case "verify":
		err = cmdVerify(args)
	case "lint":
		err = cmdLint(args)
	case "serve":
		err = cmdServe(args)
	case "agents":
		err = cmdAgents(args)
	case "-h", "--help", "help":
		usage()
		return
	default:
		fmt.Fprintf(os.Stderr, "cogo: unknown command %q\n\n", os.Args[1])
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "cogo:", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprint(os.Stderr, `cogo — the memory layer with computed confidence

usage: cogo <command> [flags] [args]

commands:
  init                 create a vault (index.md, log.md)
  add [file.md]        validate, color and store a note (stdin if no file)
  pack <query...>      print a budgeted, color-aware context digest
  search <query...>    list matching notes: color · id · summary
  stale                list notes that are stale or expiring soon
  verify <id>          mark a note's check passed, re-date and re-color
  lint                 deterministic checks + (optional) LLM contradiction scan
  serve                run as an MCP server over stdio (any LLM connects)
  agents               print an AGENTS.md/CLAUDE.md that teaches an agent the COGO protocol

common flags:
  -vault <dir>         vault directory (default $COGO_VAULT or ./vault)

put flags before positional args:  cogo pack -project fisherboy redis
`)
}

// --- shared helpers ---

func vaultFlag(fs *flag.FlagSet) *string {
	def := os.Getenv("COGO_VAULT")
	if def == "" {
		def = "vault"
	}
	return fs.String("vault", def, "vault directory")
}

func today() core.Date {
	n := time.Now()
	return core.NewDate(n.Year(), n.Month(), n.Day())
}

// resolveToday lets read-only commands pin the date for reproducible output.
func resolveToday(override string) (core.Date, error) {
	if override == "" {
		return today(), nil
	}
	return core.ParseDate(override)
}

func colorTag(c core.Color) string { return "[" + c.String() + "]" }

func sortedIDs(vault map[string]*core.Note) []string {
	ids := make([]string, 0, len(vault))
	for id := range vault {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// regenIndex rewrites index.md as a one-line-per-note catalog (§10).
func regenIndex(dir string, vault map[string]*core.Note) error {
	verdicts := core.EvaluateVault(vault, nil, today())
	var b strings.Builder
	b.WriteString("# COGO vault index\n\nOne line per note · regenerated by cogo.\n\n")
	for _, id := range sortedIDs(vault) {
		n := vault[id]
		v := verdicts[id]
		stale := v.StaleAt.String()
		if stale == "" {
			stale = "—"
		}
		fmt.Fprintf(&b, "- %s `%s` (%s/%s) stale_at:%s\n", colorTag(v.Color), id, n.Type, n.Project, stale)
	}
	return os.WriteFile(filepath.Join(dir, "index.md"), []byte(b.String()), 0o644)
}

// appendLog adds one grep-friendly line to the append-only log.md (§10).
func appendLog(dir, msg string) error {
	f, err := os.OpenFile(filepath.Join(dir, "log.md"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "- %s %s\n", time.Now().UTC().Format(time.RFC3339), msg)
	return err
}

// --- commands ---

func cmdInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	dir := vaultFlag(fs)
	_ = fs.Parse(args)

	if err := os.MkdirAll(*dir, 0o755); err != nil {
		return err
	}
	if idx := filepath.Join(*dir, "index.md"); !exists(idx) {
		if err := os.WriteFile(idx, []byte("# COGO vault index\n\nOne line per note · regenerated by cogo.\n"), 0o644); err != nil {
			return err
		}
	}
	if lg := filepath.Join(*dir, "log.md"); !exists(lg) {
		if err := os.WriteFile(lg, []byte("# COGO log\n"), 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("initialized vault at %s\n", *dir)
	return nil
}

func cmdAdd(args []string) error {
	fs := flag.NewFlagSet("add", flag.ExitOnError)
	dir := vaultFlag(fs)
	force := fs.Bool("force", false, "overwrite even a note that is currently green")
	_ = fs.Parse(args)

	var data []byte
	var err error
	if rest := fs.Args(); len(rest) == 0 || rest[0] == "-" {
		data, err = io.ReadAll(os.Stdin)
	} else {
		data, err = os.ReadFile(rest[0])
	}
	if err != nil {
		return err
	}

	note, err := core.ParseNote(data)
	if err != nil {
		return err
	}
	if note.Type == "" {
		return fmt.Errorf("note %q is missing required field: type", note.ID)
	}

	vault, err := core.LoadVault(*dir)
	if err != nil {
		return err
	}

	// Never silently overwrite a green note (§1, §8).
	existing, has := vault[note.ID]
	if has {
		if ev := core.Evaluate(existing, vault, nil, today()); ev.Color == core.Green && !*force {
			return fmt.Errorf("note %q is currently green; refusing to overwrite without -force", note.ID)
		}
	}

	vault[note.ID] = note
	v := core.Evaluate(note, vault, nil, today())
	note.Apply(v)

	path := filepath.Join(*dir, note.ID+".md")
	if has && existing.Path != "" {
		path = existing.Path
	}
	if err := core.WriteNoteFile(path, note); err != nil {
		return err
	}
	if err := regenIndex(*dir, vault); err != nil {
		return err
	}
	if err := appendLog(*dir, fmt.Sprintf("add %s %s — %s", note.ID, v.Color, v.Reason)); err != nil {
		return err
	}
	fmt.Printf("%s %s — %s\n", colorTag(v.Color), note.ID, v.Reason)
	return nil
}

func cmdPack(args []string) error {
	fs := flag.NewFlagSet("pack", flag.ExitOnError)
	dir := vaultFlag(fs)
	project := fs.String("project", "", "filter by project")
	budget := fs.Int("budget", 0, "approx token budget (0 = unlimited)")
	todayStr := fs.String("today", "", "pin the date as YYYY-MM-DD (default: real today)")
	_ = fs.Parse(args)

	t, err := resolveToday(*todayStr)
	if err != nil {
		return err
	}
	vault, err := core.LoadVault(*dir)
	if err != nil {
		return err
	}
	p := core.BuildPack(vault, nil, core.PackOptions{
		Query:   strings.Join(fs.Args(), " "),
		Project: *project,
		Budget:  *budget,
		Today:   t,
	})
	fmt.Print(p.Markdown)
	return nil
}

func cmdSearch(args []string) error {
	fs := flag.NewFlagSet("search", flag.ExitOnError)
	dir := vaultFlag(fs)
	project := fs.String("project", "", "filter by project")
	limit := fs.Int("limit", 0, "max results (0 = all)")
	todayStr := fs.String("today", "", "pin the date as YYYY-MM-DD")
	_ = fs.Parse(args)

	t, err := resolveToday(*todayStr)
	if err != nil {
		return err
	}
	vault, err := core.LoadVault(*dir)
	if err != nil {
		return err
	}
	hits := core.Search(vault, nil, strings.Join(fs.Args(), " "), *project, t, *limit, false)
	if len(hits) == 0 {
		fmt.Println("no matching notes")
		return nil
	}
	for _, h := range hits {
		fmt.Printf("%-9s %-28s %s\n", colorTag(h.Color), h.ID, h.Summary)
	}
	return nil
}

// cmdAgents emits the bootstrap file (AGENTS.md/CLAUDE.md) that teaches a coding
// agent the COGO protocol and how to connect. --digest embeds a static snapshot
// of the current green/yellow notes for an agent that can't speak MCP.
func cmdAgents(args []string) error {
	fs := flag.NewFlagSet("agents", flag.ExitOnError)
	dir := vaultFlag(fs)
	claude := fs.Bool("claude", false, "name it CLAUDE.md (Claude Code) instead of AGENTS.md")
	httpURL := fs.String("http", "", "MCP-over-HTTP endpoint for the connection snippet (else a stdio snippet)")
	digest := fs.Bool("digest", false, "embed a static snapshot of the current green/yellow notes")
	out := fs.String("o", "", "write to this file instead of stdout")
	todayStr := fs.String("today", "", "pin the date as YYYY-MM-DD")
	_ = fs.Parse(args)

	name := "AGENTS.md"
	if *claude {
		name = "CLAUDE.md"
	}
	opts := agentsmd.Options{Filename: name, HTTPURL: *httpURL, Vault: *dir}
	if *httpURL == "" {
		if exe, err := os.Executable(); err == nil {
			opts.Binary = exe
		}
	}
	if *digest {
		t, err := resolveToday(*todayStr)
		if err != nil {
			return err
		}
		vault, err := core.LoadVault(*dir)
		if err != nil {
			return err
		}
		core.ResolveEvidence(vault, core.LoadEvidenceRoots(*dir))
		verdicts := core.EvaluateVault(vault, contra.Open(*dir).OpenNoteSet(), t)
		items := make([]agentsmd.DigestItem, 0, len(vault))
		for id, n := range vault {
			if n.Status != "" {
				continue // skip archived/retracted — the snapshot is the live memory
			}
			items = append(items, agentsmd.DigestItem{Color: verdicts[id].Color.String(), ID: id, Claim: core.Claim(n)})
		}
		sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
		opts.Digest = agentsmd.RenderDigest(items)
		opts.Date = t.String()
	}
	md := agentsmd.Generate(opts)
	if *out != "" {
		if err := os.WriteFile(*out, []byte(md), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
		return nil
	}
	fmt.Print(md)
	return nil
}

func cmdStale(args []string) error {
	fs := flag.NewFlagSet("stale", flag.ExitOnError)
	dir := vaultFlag(fs)
	within := fs.Int("within", 30, "also list notes going stale within N days")
	todayStr := fs.String("today", "", "pin the date as YYYY-MM-DD")
	_ = fs.Parse(args)

	t, err := resolveToday(*todayStr)
	if err != nil {
		return err
	}
	vault, err := core.LoadVault(*dir)
	if err != nil {
		return err
	}
	verdicts := core.EvaluateVault(vault, nil, t)

	type row struct {
		id, status, typ string
		stale           core.Date
		color           core.Color
	}
	var rows []row
	for id, n := range vault {
		v := verdicts[id]
		if v.StaleAt.IsZero() { // mistakes and undated notes don't decay
			continue
		}
		days := int(v.StaleAt.Time().Sub(t.Time()).Hours() / 24)
		switch {
		case days < 0:
			rows = append(rows, row{id, "stale", n.Type, v.StaleAt, v.Color})
		case days <= *within:
			rows = append(rows, row{id, "soon", n.Type, v.StaleAt, v.Color})
		}
	}
	if len(rows) == 0 {
		fmt.Println("nothing stale or expiring soon")
		return nil
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].stale.Before(rows[j].stale) })
	for _, r := range rows {
		fmt.Printf("%-6s %-9s %s  %-28s %s\n", r.status, colorTag(r.color), r.stale, r.id, r.typ)
	}
	return nil
}

func cmdVerify(args []string) error {
	fs := flag.NewFlagSet("verify", flag.ExitOnError)
	dir := vaultFlag(fs)
	_ = fs.Parse(args)
	rest := fs.Args()
	if len(rest) != 1 {
		return fmt.Errorf("usage: cogo verify <id>")
	}
	id := rest[0]

	vault, err := core.LoadVault(*dir)
	if err != nil {
		return err
	}
	note, ok := vault[id]
	if !ok {
		return fmt.Errorf("no note with id %q", id)
	}

	// Revalidate: the check passed, as of today. Re-color from there.
	note.Check.Status = "passed"
	note.LastVerified = today()
	v := core.Evaluate(note, vault, nil, today())
	note.Apply(v)

	path := note.Path
	if path == "" {
		path = filepath.Join(*dir, id+".md")
	}
	if err := core.WriteNoteFile(path, note); err != nil {
		return err
	}
	if err := regenIndex(*dir, vault); err != nil {
		return err
	}
	if err := appendLog(*dir, fmt.Sprintf("verify %s %s", id, v.Color)); err != nil {
		return err
	}
	fmt.Printf("%s %s — %s\n", colorTag(v.Color), id, v.Reason)
	return nil
}
