// Code generated by internal/confidence/gen. NO EDITAR A MANO.
//
// Se genera desde transitions.yaml, que es la fuente única de la máquina de
// estados. Para cambiar algo, editá ese archivo y corré:
//
//	go generate ./internal/confidence

package confidence

// Estado de evidencia de una nota.
type Estado uint8

const (
	// Excluida del pack por decisión explícita.
	Quarantined Estado = 0
	// El check se ejecutó y falló.
	Refuted Estado = 1
	// Hay una contradicción abierta con otra nota.
	Contradicted Estado = 2
	// Venció su ventana de frescura, o cambió de forma material una evidencia.
	Stale Estado = 3
	// Capturada, sin criterio de verificación declarado.
	Asserted Estado = 4
	// Hay un criterio de verificación; todavía no se ejecutó ni se declaró.
	CheckDeclared Estado = 5
	// Alguien declaró que el check pasa. Es verde porque el color mide cuánto sostiene la evidencia, y la evidencia sostiene; que nadie lo haya ejecutado lo dice la procedencia, no el color.
	ClaimedPassed Estado = 6
	// El runner interno ejecutó el check y registró su código de salida.
	Verified Estado = 7
	// Se tomó el lease y la ejecución está en curso.
	Verifying Estado = 8
)

func (e Estado) String() string {
	switch e {
	case Quarantined:
		return "quarantined"
	case Refuted:
		return "refuted"
	case Contradicted:
		return "contradicted"
	case Stale:
		return "stale"
	case Asserted:
		return "asserted"
	case CheckDeclared:
		return "check_declared"
	case ClaimedPassed:
		return "claimed_passed"
	case Verified:
		return "verified"
	case Verifying:
		return "verifying"
	}
	return "desconocido"
}

// Color es la PROYECCIÓN del estado: lo que ve una persona. Dos estados
// distintos pueden proyectar el mismo color a propósito — la máquina distingue
// situaciones que el semáforo no necesita distinguir.
func (e Estado) Color() string {
	switch e {
	case Quarantined:
		return "red"
	case Refuted:
		return "red"
	case Contradicted:
		return "red"
	case Stale:
		return "yellow"
	case Asserted:
		return "yellow"
	case CheckDeclared:
		return "yellow"
	case ClaimedPassed:
		return "green"
	case Verified:
		return "green"
	case Verifying:
		return "yellow"
	}
	return "ungraded"
}

// Rango es la posición en el retículo de confianza: mayor es más confiable.
// Los estados transitorios devuelven -1 y no participan de la propagación.
func (e Estado) Rango() int {
	switch e {
	case Quarantined:
		return 0
	case Refuted:
		return 1
	case Contradicted:
		return 2
	case Stale:
		return 3
	case Asserted:
		return 4
	case CheckDeclared:
		return 5
	case ClaimedPassed:
		return 6
	case Verified:
		return 7
	case Verifying:
		return -1
	}
	return -1
}

// Transitorio dice si el estado es de paso. Un estado transitorio no está en
// el retículo: una nota que se está verificando no debe arrastrar a sus
// dependientes ni hacer parpadear sus colores mientras corre.
func (e Estado) Transitorio() bool { return e.Rango() < 0 }

// Meet es la combinación del retículo. Como el orden es total, es el mínimo: de
// dos respaldos, vale el más débil. Es lo que hace que la duda se propague.
func Meet(a, b Estado) Estado {
	if a.Rango() <= b.Rango() {
		return a
	}
	return b
}

// Evento es lo que puede cambiar el estado de una nota.
type Evento string

const (
	// Se declaró un criterio de verificación para la nota.
	EvCheckDeclared Evento = "CheckDeclared"
	// Se tomó el lease y empieza la ejecución.
	EvVerificationStarted Evento = "VerificationStarted"
	// El runner interno corrió el check y observó su código de salida.
	EvCheckExecuted Evento = "CheckExecuted"
	// Alguien afirma que el check pasa, sin ejecutarlo.
	EvVerifyDeclared Evento = "VerifyDeclared"
	// Venció la ventana de frescura de la nota.
	EvTTLExpired Evento = "TTLExpired"
	// Cambió de forma material una evidencia en la que la nota se apoya.
	EvAnchorMaterialChange Evento = "AnchorMaterialChange"
	// El análisis encontró una contradicción con otra nota.
	EvContradictionOpened Evento = "ContradictionOpened"
	// La contradicción se cerró o se descartó.
	EvContradictionResolved Evento = "ContradictionResolved"
	// Se excluyó la nota del pack por decisión explícita.
	EvQuarantined Evento = "Quarantined"
	// Se levantó la cuarentena.
	EvUnquarantined Evento = "Unquarantined"
)

// Guarda discrimina entre transiciones que salen del mismo estado con el
// mismo evento. Las de una misma decisión son excluyentes entre sí.
type Guarda string

const (
	// Código de salida 0, emitido por el runner interno, con los anchors íntegros.
	GEjecucionOk Guarda = "ejecucion_ok"
	// Código de salida distinto de 0.
	GEjecucionFalla Guarda = "ejecucion_falla"
	// Lo declara un agente o una persona. Nunca alcanza `verified`.
	GDeclaraUnTercero Guarda = "declara_un_tercero"
	// Lo emite el runner interno; se resuelve por resultado_de_ejecucion.
	GDeclaraElRunner Guarda = "declara_el_runner"
)

// Transicion es una arista de la máquina. Desde vacío significa "desde
// cualquier estado no transitorio".
type Transicion struct {
	Desde  Estado
	Hasta  Estado
	Evento Evento
	Guarda Guarda
	Any    bool // aplica desde cualquier estado
}

// Tabla es la máquina completa, en el orden en que se declaró.
var Tabla = []Transicion{
	{Desde: Asserted, Hasta: CheckDeclared, Evento: EvCheckDeclared},
	{Desde: CheckDeclared, Hasta: Verifying, Evento: EvVerificationStarted},
	{Desde: Stale, Hasta: Verifying, Evento: EvVerificationStarted},
	{Desde: Verifying, Hasta: Verified, Evento: EvCheckExecuted, Guarda: GEjecucionOk},
	{Desde: Verifying, Hasta: Refuted, Evento: EvCheckExecuted, Guarda: GEjecucionFalla},
	{Desde: CheckDeclared, Hasta: ClaimedPassed, Evento: EvVerifyDeclared, Guarda: GDeclaraUnTercero},
	{Desde: Stale, Hasta: ClaimedPassed, Evento: EvVerifyDeclared, Guarda: GDeclaraUnTercero},
	{Any: true, Hasta: Stale, Evento: EvTTLExpired},
	{Any: true, Hasta: Stale, Evento: EvAnchorMaterialChange},
	{Any: true, Hasta: Contradicted, Evento: EvContradictionOpened},
	{Any: true, Hasta: Quarantined, Evento: EvQuarantined},
	{Desde: Refuted, Hasta: CheckDeclared, Evento: EvCheckDeclared},
	{Desde: Contradicted, Hasta: CheckDeclared, Evento: EvContradictionResolved},
	{Desde: Quarantined, Hasta: Asserted, Evento: EvUnquarantined},
}

// Inicial es el estado de una nota recién capturada.
const Inicial = Asserted
