package suasion

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"testing"

	"github.com/diegoparras/cogo/internal/core"
	"github.com/diegoparras/cogo/internal/llm"
)

// Blind calibration corpus: 100 cases generated by red-team agents that never
// saw the ontology markers (ground truth = the generator's intent), so recall
// here is not circular. TestRedTeamDeterministic runs in the normal suite as a
// regression guard (the crown-jewel invariant: no benign turn goes red);
// TestRedTeamTier1 is opt-in (RUN_TIER1=1 + COGO_LLM_*) and measures the model
// tier's recall gain and false-positive cost.

type rtCase struct {
	ID         string   `json:"id"`
	Kind       string   `json:"kind"`
	Discipline string   `json:"discipline"`
	Difficulty string   `json:"difficulty"`
	Turn       string   `json:"turn"`
	Transcript []Turn   `json:"transcript"`
	Mandate    *Mandate `json:"mandate"`
	Note       string   `json:"note"`
}

func loadRedTeam(t *testing.T) []rtCase {
	t.Helper()
	b, err := os.ReadFile("testdata/redteam.json")
	if err != nil {
		t.Fatal(err)
	}
	var cs []rtCase
	if err := json.Unmarshal(b, &cs); err != nil {
		t.Fatal(err)
	}
	return cs
}

func caught(c core.Color) bool { return c >= core.Yellow } // Green=1 < Yellow=2 <= Red=3

func TestRedTeamDeterministic(t *testing.T) {
	e := testEngine(t)
	cs := loadRedTeam(t)

	var (
		manip, manipCaught, manipRed                 int
		easyN, easyCaught, hardN, hardCaught         int
		benign, benignGreen, benignYellow, benignRed int
		plainN, plainClean, trapN, trapNotRed        int
	)
	var redFPs, missedManip []rtCase

	for _, c := range cs {
		r := e.Analyze(c.Turn, c.Transcript, c.Mandate)
		switch c.Kind {
		case "manip":
			manip++
			if caught(r.Overall) {
				manipCaught++
			} else {
				missedManip = append(missedManip, c)
			}
			if r.Overall == core.Red {
				manipRed++
			}
			switch c.Difficulty {
			case "easy":
				easyN++
				if caught(r.Overall) {
					easyCaught++
				}
			case "hard":
				hardN++
				if caught(r.Overall) {
					hardCaught++
				}
			}
		case "benign":
			benign++
			switch r.Overall {
			case core.Green, core.Ungraded:
				benignGreen++
			case core.Yellow:
				benignYellow++
			case core.Red:
				benignRed++
				redFPs = append(redFPs, c)
			}
			switch c.Difficulty {
			case "plain":
				plainN++
				if r.Overall <= core.Green {
					plainClean++
				}
			case "trap":
				trapN++
				if r.Overall != core.Red {
					trapNotRed++
				}
			}
		}
	}

	pct := func(a, b int) string {
		if b == 0 {
			return "n/a"
		}
		return fmt.Sprintf("%d/%d (%.0f%%)", a, b, 100*float64(a)/float64(b))
	}

	t.Logf("====== RED-TEAM CIEGO · %d casos (motor DETERMINISTA, sin modelo) ======", len(cs))
	t.Logf("")
	t.Logf("MANIPULATIVOS (%d) — recall = atrapados (amarillo o rojo):", manip)
	t.Logf("  total atrapados:   %s", pct(manipCaught, manip))
	t.Logf("  llegaron a rojo:   %s", pct(manipRed, manip))
	t.Logf("  faciles atrapados: %s", pct(easyCaught, easyN))
	t.Logf("  DIFICILES atrap.:  %s   <- el alcance real del lexicon", pct(hardCaught, hardN))
	t.Logf("")
	t.Logf("BENIGNOS (%d) — falsos positivos:", benign)
	t.Logf("  verdes (limpio):        %s", pct(benignGreen, benign))
	t.Logf("  amarillos (FP blando):  %s", pct(benignYellow, benign))
	t.Logf("  ROJOS (FP caro):        %s   <- el que rompe la confianza", pct(benignRed, benign))
	t.Logf("  'plain' quedaron limpios: %s", pct(plainClean, plainN))
	t.Logf("  'trap' evitaron el rojo:  %s", pct(trapNotRed, trapN))
	t.Logf("")
	if len(redFPs) > 0 {
		t.Logf("--- FALSOS POSITIVOS ROJOS (benignos marcados rojo) ---")
		for _, c := range redFPs {
			t.Logf("  [%s/%s] %s", c.ID, c.Difficulty, c.Turn)
			t.Logf("        (nota: %s)", c.Note)
		}
		t.Logf("")
	}
	sort.Slice(missedManip, func(a, b int) bool { return missedManip[a].ID < missedManip[b].ID })
	t.Logf("manipulativos que el determinista NO atrapó: %d", len(missedManip))

	// The invariant that must never regress: the deterministic layer never
	// red-flags benign text. Low recall is acceptable (the model tier covers it);
	// a benign turn flagged red is not.
	if benignRed > 0 {
		t.Errorf("deterministic RED false positives: %d — a benign turn must never be red", benignRed)
	}
}

// deterministicMisses recomputes, with no model, which manipulative cases the
// engine fails to flag — so the Tier-1 pass always measures against the current
// code, not a stale file.
func deterministicMisses(e *Engine, cs []rtCase) []rtCase {
	var out []rtCase
	for _, c := range cs {
		if c.Kind != "manip" {
			continue
		}
		if !caught(e.Analyze(c.Turn, c.Transcript, c.Mandate).Overall) {
			out = append(out, c)
		}
	}
	return out
}

// TestRedTeamTier1 runs a model (from COGO_LLM_* env) over the deterministic
// misses to see how many the structural tier rescues, AND over the benign cases
// to see whether the model tier ADDS false positives. Slow; opt-in RUN_TIER1=1.
func TestRedTeamTier1(t *testing.T) {
	if os.Getenv("RUN_TIER1") == "" {
		t.Skip("set RUN_TIER1=1 and COGO_LLM_* env")
	}
	prov := llm.FromEnv()
	if !prov.Available() {
		t.Fatal("set COGO_LLM_BASE_URL / COGO_LLM_MODEL / COGO_LLM_API_KEY")
	}
	e := testEngine(t)
	ctx := context.Background()
	all := loadRedTeam(t)

	// (1) recall gain: model over the deterministic misses (recomputed live).
	missed := deterministicMisses(e, all)
	rescued, hardResc, hardTot := 0, 0, 0
	for _, c := range missed {
		if c.Difficulty == "hard" {
			hardTot++
		}
		r := e.AnalyzeWith(ctx, c.Turn, c.Transcript, c.Mandate, Opts{Tier1: prov})
		if caught(r.Overall) {
			rescued++
			if c.Difficulty == "hard" {
				hardResc++
			}
			t.Logf("  RESCATADO [%s/%s]: %.90s", c.ID, c.Difficulty, c.Turn)
		}
	}

	// (2) FP cost: model over the benign cases — does turning it on cry wolf?
	var benTot, benGreen, benYellow, benRed int
	for _, c := range all {
		if c.Kind != "benign" {
			continue
		}
		benTot++
		r := e.AnalyzeWith(ctx, c.Turn, c.Transcript, c.Mandate, Opts{Tier1: prov})
		switch r.Overall {
		case core.Red:
			benRed++
			t.Logf("  FP-ROJO benigno [%s/%s]: %.90s", c.ID, c.Difficulty, c.Turn)
		case core.Yellow:
			benYellow++
		default:
			benGreen++
		}
	}

	t.Logf("====== TIER-1 (%s) ======", prov.Name())
	detCaught := 50 - len(missed)
	t.Logf("RESCATE sobre %d misses del determinista: %d rescatados (hard: %d/%d)", len(missed), rescued, hardResc, hardTot)
	t.Logf("RECALL COMBINADO (%d determinista + %d modelo)/50 = %d/50 (%.0f%%)", detCaught, rescued, detCaught+rescued, 100*float64(detCaught+rescued)/50)
	t.Logf("FP con modelo ON sobre %d benignos: verde %d · amarillo %d · ROJO %d", benTot, benGreen, benYellow, benRed)
}
